settings:
  title: 'Estado de servicios (TuSemana)'
  url: 'https://estado.tusemana.com/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos los servidores de TuSemana est치n operando correctamente'
  notAllmonitorsOperational: 'Se identifica un error, se est치 investigando'
  monitorLabelOperational: 'Operando'
  monitorLabelNotOperational: 'Sin operar'
  monitorLabelNoData: 'Sin datos'
  dayInHistogramNoData: 'Sin datos'
  dayInHistogramOperational: 'Todo en orden'
  dayInHistogramNotOperational: ' incidente(s)' # xx incident(s) recorded

monitors:
  - id: pagina-principal
    name: tusemana.com
    description: 'P치gina principal de TuSemana'
    url: 'https://tusemana.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    #linkable: false

  - id: pagina-registro
    name: registro.tusemana.com
    description: 'P치gina de registro para nuevos clientes.'
    url: 'https://registro.tusemana.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: servidor-1
    name: Servidor 1
    url: 'https://fernandodilland.com/'
    method: GET
    expectStatus: 200
    linkable: false

  - id: servidor-2
    name: Servidor 2
    url: 'https://niqera.com/'
    method: GET
    expectStatus: 200
    linkable: false
