settings:
  title: 'Estado de servicios (TuSemana)'
  url: 'https://estado.tusemana.com/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos los servidores de TuSemana están operando correctamente'
  notAllmonitorsOperational: 'Se identifica un error, se está investigando'
  monitorLabelOperational: 'Operando'
  monitorLabelNotOperational: 'Sin operar'
  monitorLabelNoData: 'Sin datos'
  dayInHistogramNoData: 'Sin datos'
  dayInHistogramOperational: 'Todo en orden'
  dayInHistogramNotOperational: ' incidente(s)' # xx incident(s) recorded

monitors:
  - id: pagina-principal
    name: tusemana.com
    description: 'Página principal de TuSemana'
    url: 'https://tusemana.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
