export const locations = {
  ADL: 'servidor Adelaide',
  AKL: 'servidor Auckland',
  ALG: 'servidor Argel',
  AMM: 'servidor Amán',
  AMS: 'servidor Ámsterdam',
  ARI: 'servidor Arica',
  ARN: 'servidor Estocolmo',
  ASU: 'servidor Asunción',
  ATH: 'servidor Atenas',
  ATL: 'servidor Atlanta',
  BAH: 'servidor Manama',
  BCN: 'servidor Barcelona',
  BEG: 'servidor Belgrado',
  BEL: 'servidor Belén',
  BEY: 'servidor Beirut',
  BGW: 'servidor Bagdad',
  BKK: 'servidor Bangkok',
  BLR: 'servidor Bangalore',
  BNA: 'servidor Nashville',
  BNE: 'servidor Brisbane',
  BNU: 'servidor Blumenau',
  BOG: 'servidor Bogotá',
  BOM: 'servidor Mumbai',
  BOS: 'servidor Boston',
  BRU: 'servidor Bruselas',
  BSB: 'servidor Brasilia',
  BUD: 'servidor Budapest',
  BUF: 'servidor Búfalo',
  BWN: 'servidor Bandar Seri Begawan',
  CAN: 'servidor Cantón',
  CBR: 'servidor Canberra',
  CCU: 'servidor Calcuta',
  CDG: 'servidor París',
  CEB: 'servidor Cebú',
  CFC: 'servidor Caçador',
  CGK: 'servidor Yakarta',
  CGO: 'servidor Zhengzhou',
  CGP: 'servidor Chittagong',
  CKG: 'servidor Chongqing',
  CLT: 'servidor Charlotte',
  CMB: 'servidor Colombo',
  CMH: 'servidor Columbus',
  CMN: 'servidor Casablanca',
  CNF: 'servidor Belo Horizonte',
  CPH: 'servidor Copenhague',
  CPT: 'servidor Ciudad del Cabo',
  CSX: 'servidor Zhuzhou',
  CTU: 'servidor Chengdu',
  CUR: 'servidor Willemstad',
  CWB: 'servidor Curitiba',
  DAC: 'servidor Daca',
  DAR: 'servidor Dar es Salaam',
  DEL: 'servidor Nueva Delhi',
  DEN: 'servidor Denver',
  DFW: 'servidor Dallas',
  DKR: 'servidor Dakar',
  DME: 'servidor Moscú',
  DMM: 'servidor Dammam',
  DOH: 'servidor Doha',
  DTW: 'servidor Detroit',
  DUB: 'servidor Dublín',
  DUR: 'servidor Durban',
  DUS: 'servidor Düsseldorf',
  DXB: 'servidor Dubái',
  EDI: 'servidor Edimburgo',
  EVN: 'servidor Ereván',
  EWR: 'servidor Newark',
  EZE: 'servidor Buenos Aires',
  FCO: 'servidor Roma',
  FLN: 'servidor Florianópolis',
  FOR: 'servidor Fortaleza',
  FRA: 'servidor Fráncfort',
  GIG: 'servidor Río de Janeiro',
  GND: 'servidor San Jorge',
  GOT: 'servidor Gotemburgo',
  GRU: 'servidor São Paulo',
  GUA: 'servidor Ciudad de Guatemala',
  GVA: 'servidor Ginebra',
  GYD: 'servidor Bakú',
  GYE: 'servidor Guayaquil',
  HAM: 'servidor Hamburgo',
  HAN: 'servidor Hanói',
  HEL: 'servidor Helsinki',
  HKG: 'servidor Hong Kong',
  HNL: 'servidor Honolulu',
  HRE: 'servidor Harare',
  HYD: 'servidor Hyderabad',
  IAD: 'servidor Ashburn',
  IAH: 'servidor Houston',
  ICN: 'servidor Seúl',
  IND: 'servidor Indianápolis',
  ISB: 'servidor Islamabad',
  IST: 'servidor Estambul',
  ITJ: 'servidor Itajaí',
  JAX: 'servidor Jacksonville',
  JIB: 'servidor Ciudad de Yibuti',
  JNB: 'servidor Johannesburgo',
  JSR: 'servidor Jashore',
  KBP: 'servidor Kiev',
  KEF: 'servidor Reikiavik',
  KGL: 'servidor Kigali',
  KHI: 'servidor Karachi',
  KIV: 'servidor Chisináu',
  KIX: 'servidor Osaka',
  KJA: 'servidor Krasnoyarsk',
  KTM: 'servidor Katmandú',
  KUL: 'servidor Kuala Lumpur',
  KWI: 'servidor Ciudad de Kuwait',
  LAD: 'servidor Luanda',
  LAS: 'servidor Las Vegas',
  LAX: 'servidor Los Ángeles',
  LCA: 'servidor Nicosia',
  LED: 'servidor San Petersburgo',
  LHE: 'servidor Lahore',
  LHR: 'servidor Londres',
  LIM: 'servidor Lima',
  LIS: 'servidor Lisboa',
  LOS: 'servidor Lagos',
  LUX: 'servidor Ciudad de Luxemburgo',
  MAA: 'servidor Chennai',
  MAD: 'servidor Madrid',
  MAN: 'servidor Mánchester',
  MBA: 'servidor Mombasa',
  MCI: 'servidor Kansas City',
  MCT: 'servidor Mascate',
  MDE: 'servidor Medellín',
  MEL: 'servidor Melbourne',
  MEM: 'servidor Memphis',
  MEX: 'servidor Ciudad de México',
  MFE: 'servidor McAllen',
  MFM: 'servidor Macao',
  MGM: 'servidor Montgomery',
  MIA: 'servidor Miami',
  MLE: 'servidor Malé',
  MNL: 'servidor Manila',
  MPM: 'servidor Maputo',
  MRS: 'servidor Marsella',
  MRU: 'servidor Puerto Luis',
  MSP: 'servidor Minneapolis',
  MUC: 'servidor Múnich',
  MXP: 'servidor Milán',
  NAG: 'servidor Nagpur',
  NBG: 'servidor Ningbo',
  NBO: 'servidor Nairobi',
  NOU: 'servidor Numea',
  NRT: 'servidor Tokio',
  OMA: 'servidor Omaha',
  ORD: 'servidor Chicago',
  ORF: 'servidor Norfolk',
  OSL: 'servidor Oslo',
  OTP: 'servidor Bucarest',
  PAP: 'servidor Puerto Príncipe',
  PBH: 'servidor Timbu',
  PBM: 'servidor Paramaribo',
  PDX: 'servidor Portland',
  PER: 'servidor Perth',
  PHL: 'servidor Filadelfia',
  PHX: 'servidor Phoenix',
  PIT: 'servidor Pittsburgh',
  PMO: 'servidor Palermo',
  PNH: 'servidor Phnom Penh',
  POA: 'servidor Porto Alegre',
  PRG: 'servidor Praga',
  PTY: 'servidor Ciudad de Panamá',
  QRO: 'servidor Querétaro',
  QWJ: 'servidor Americana',
  RAO: 'servidor Ribeirão Preto',
  RGN: 'servidor Rangún',
  RIC: 'servidor Richmond',
  RIX: 'servidor Riga',
  ROB: 'servidor Monrovia',
  RUH: 'servidor Riad',
  RUN: 'servidor Reunión',
  SAN: 'servidor San Diego',
  SCL: 'servidor Santiago',
  SEA: 'servidor Seattle',
  SGN: 'servidor Ciudad Ho Chi Minh',
  SHA: 'servidor Shanghái',
  SIN: 'servidor Singapur',
  SJC: 'servidor San José',
  SJO: 'servidor San José',
  SJP: 'servidor São José do Rio Preto',
  SKG: 'servidor Tesalónica',
  SLC: 'servidor Salt Lake City',
  SMF: 'servidor Sacramento',
  SOD: 'servidor Sorocaba',
  SOF: 'servidor Sofía',
  SSA: 'servidor Salvador',
  STL: 'servidor San Luis',
  SVX: 'servidor Ekaterimburgo',
  SYD: 'servidor Sídney',
  SZV: 'servidor Suzhou',
  TBS: 'servidor Tiflis',
  TGU: 'servidor Tegucigalpa',
  TLH: 'servidor Tallahassee',
  TLL: 'servidor Tallin',
  TLV: 'servidor Tel Aviv',
  TNA: 'servidor Jinan',
  TNR: 'servidor Antananarivo',
  TPA: 'servidor Tampa',
  TPE: 'servidor Taipéi',
  TSN: 'servidor Tianjin',
  TUN: 'servidor Túnez',
  TXL: 'servidor Berlín',
  UIO: 'servidor Quito',
  ULN: 'servidor Ulán Bator',
  URT: 'servidor Surat Thani',
  VCP: 'servidor Campinas',
  VIE: 'servidor Viena',
  VNO: 'servidor Vilna',
  VTE: 'servidor Vientián',
  WAW: 'servidor Varsovia',
  WUH: 'servidor Wuhan',
  WUX: 'servidor Wuxi',
  XIY: 'servidor Xi an',
  YUL: 'servidor Montreal',
  YVR: 'servidor Vancouver',
  YWG: 'servidor Winnipeg',
  YXE: 'servidor Saskatoon',
  YYC: 'servidor Calgary',
  YYZ: 'servidor Toronto',
  ZAG: 'servidor Zagreb',
  ZDM: 'servidor Ramallah',
  ZRH: 'servidor Zúrich',
};
