export const locations = {
  ADL: 'servidor de Adelaide',
  AKL: 'servidor de Auckland',
  ALG: 'servidor de Argel',
  AMM: 'servidor de Amán',
  AMS: 'servidor de Ámsterdam',
  ARI: 'servidor de Arica',
  ARN: 'servidor de Estocolmo',
  ASU: 'servidor de Asunción',
  ATH: 'servidor de Atenas',
  ATL: 'servidor de Atlanta',
  BAH: 'servidor de Manama',
  BCN: 'servidor de Barcelona',
  BEG: 'servidor de Belgrado',
  BEL: 'servidor de Belén',
  BEY: 'servidor de Beirut',
  BGW: 'servidor de Bagdad',
  BKK: 'servidor de Bangkok',
  BLR: 'servidor de Bangalore',
  BNA: 'servidor de Nashville',
  BNE: 'servidor de Brisbane',
  BNU: 'servidor de Blumenau',
  BOG: 'servidor de Bogotá',
  BOM: 'servidor de Mumbai',
  BOS: 'servidor de Boston',
  BRU: 'servidor de Bruselas',
  BSB: 'servidor de Brasilia',
  BUD: 'servidor de Budapest',
  BUF: 'servidor de Búfalo',
  BWN: 'servidor de Bandar Seri Begawan',
  CAN: 'servidor de Cantón',
  CBR: 'servidor de Canberra',
  CCU: 'servidor de Calcuta',
  CDG: 'servidor de París',
  CEB: 'servidor de Cebú',
  CFC: 'servidor de Caçador',
  CGK: 'servidor de Yakarta',
  CGO: 'servidor de Zhengzhou',
  CGP: 'servidor de Chittagong',
  CKG: 'servidor de Chongqing',
  CLT: 'servidor de Charlotte',
  CMB: 'servidor de Colombo',
  CMH: 'servidor de Columbus',
  CMN: 'servidor de Casablanca',
  CNF: 'servidor de Belo Horizonte',
  CPH: 'servidor de Copenhague',
  CPT: 'servidor de Ciudad del Cabo',
  CSX: 'servidor de Zhuzhou',
  CTU: 'servidor de Chengdu',
  CUR: 'servidor de Willemstad',
  CWB: 'servidor de Curitiba',
  DAC: 'servidor de Daca',
  DAR: 'servidor de Dar es Salaam',
  DEL: 'servidor de Nueva Delhi',
  DEN: 'servidor de Denver',
  DFW: 'servidor de Dallas',
  DKR: 'servidor de Dakar',
  DME: 'servidor de Moscú',
  DMM: 'servidor de Dammam',
  DOH: 'servidor de Doha',
  DTW: 'servidor de Detroit',
  DUB: 'servidor de Dublín',
  DUR: 'servidor de Durban',
  DUS: 'servidor de Düsseldorf',
  DXB: 'servidor de Dubái',
  EDI: 'servidor de Edimburgo',
  EVN: 'servidor de Ereván',
  EWR: 'servidor de Newark',
  EZE: 'servidor de Buenos Aires',
  FCO: 'servidor de Roma',
  FLN: 'servidor de Florianópolis',
  FOR: 'servidor de Fortaleza',
  FRA: 'servidor de Fráncfort',
  GIG: 'servidor de Río de Janeiro',
  GND: 'servidor de San Jorge',
  GOT: 'servidor de Gotemburgo',
  GRU: 'servidor de São Paulo',
  GUA: 'servidor de Ciudad de Guatemala',
  GVA: 'servidor de Ginebra',
  GYD: 'servidor de Bakú',
  GYE: 'servidor de Guayaquil',
  HAM: 'servidor de Hamburgo',
  HAN: 'servidor de Hanói',
  HEL: 'servidor de Helsinki',
  HKG: 'servidor de Hong Kong',
  HNL: 'servidor de Honolulu',
  HRE: 'servidor de Harare',
  HYD: 'servidor de Hyderabad',
  IAD: 'servidor de Ashburn',
  IAH: 'servidor de Houston',
  ICN: 'servidor de Seúl',
  IND: 'servidor de Indianápolis',
  ISB: 'servidor de Islamabad',
  IST: 'servidor de Estambul',
  ITJ: 'servidor de Itajaí',
  JAX: 'servidor de Jacksonville',
  JIB: 'servidor de Ciudad de Yibuti',
  JNB: 'servidor de Johannesburgo',
  JSR: 'servidor de Jashore',
  KBP: 'servidor de Kiev',
  KEF: 'servidor de Reikiavik',
  KGL: 'servidor de Kigali',
  KHI: 'servidor de Karachi',
  KIV: 'servidor de Chisináu',
  KIX: 'servidor de Osaka',
  KJA: 'servidor de Krasnoyarsk',
  KTM: 'servidor de Katmandú',
  KUL: 'servidor de Kuala Lumpur',
  KWI: 'servidor de Ciudad de Kuwait',
  LAD: 'servidor de Luanda',
  LAS: 'servidor de Las Vegas',
  LAX: 'servidor de Los Ángeles',
  LCA: 'servidor de Nicosia',
  LED: 'servidor de San Petersburgo',
  LHE: 'servidor de Lahore',
  LHR: 'servidor de Londres',
  LIM: 'servidor de Lima',
  LIS: 'servidor de Lisboa',
  LOS: 'servidor de Lagos',
  LUX: 'servidor de Ciudad de Luxemburgo',
  MAA: 'servidor de Chennai',
  MAD: 'servidor de Madrid',
  MAN: 'servidor de Mánchester',
  MBA: 'servidor de Mombasa',
  MCI: 'servidor de Kansas City',
  MCT: 'servidor de Mascate',
  MDE: 'servidor de Medellín',
  MEL: 'servidor de Melbourne',
  MEM: 'servidor de Memphis',
  MEX: 'servidor de Ciudad de México',
  MFE: 'servidor de McAllen',
  MFM: 'servidor de Macao',
  MGM: 'servidor de Montgomery',
  MIA: 'servidor de Miami',
  MLE: 'servidor de Malé',
  MNL: 'servidor de Manila',
  MPM: 'servidor de Maputo',
  MRS: 'servidor de Marsella',
  MRU: 'servidor de Puerto Luis',
  MSP: 'servidor de Minneapolis',
  MUC: 'servidor de Múnich',
  MXP: 'servidor de Milán',
  NAG: 'servidor de Nagpur',
  NBG: 'servidor de Ningbo',
  NBO: 'servidor de Nairobi',
  NOU: 'servidor de Numea',
  NRT: 'servidor de Tokio',
  OMA: 'servidor de Omaha',
  ORD: 'servidor de Chicago',
  ORF: 'servidor de Norfolk',
  OSL: 'servidor de Oslo',
  OTP: 'servidor de Bucarest',
  PAP: 'servidor de Puerto Príncipe',
  PBH: 'servidor de Timbu',
  PBM: 'servidor de Paramaribo',
  PDX: 'servidor de Portland',
  PER: 'servidor de Perth',
  PHL: 'servidor de Filadelfia',
  PHX: 'servidor de Phoenix',
  PIT: 'servidor de Pittsburgh',
  PMO: 'servidor de Palermo',
  PNH: 'servidor de Phnom Penh',
  POA: 'servidor de Porto Alegre',
  PRG: 'servidor de Praga',
  PTY: 'servidor de Ciudad de Panamá',
  QRO: 'servidor de Querétaro',
  QWJ: 'servidor de Americana',
  RAO: 'servidor de Ribeirão Preto',
  RGN: 'servidor de Rangún',
  RIC: 'servidor de Richmond',
  RIX: 'servidor de Riga',
  ROB: 'servidor de Monrovia',
  RUH: 'servidor de Riad',
  RUN: 'servidor de Reunión',
  SAN: 'servidor de San Diego',
  SCL: 'servidor de Santiago',
  SEA: 'servidor de Seattle',
  SGN: 'servidor de Ciudad Ho Chi Minh',
  SHA: 'servidor de Shanghái',
  SIN: 'servidor de Singapur',
  SJC: 'servidor de San José',
  SJO: 'servidor de San José',
  SJP: 'servidor de São José do Rio Preto',
  SKG: 'servidor de Tesalónica',
  SLC: 'servidor de Salt Lake City',
  SMF: 'servidor de Sacramento',
  SOD: 'servidor de Sorocaba',
  SOF: 'servidor de Sofía',
  SSA: 'servidor de Salvador',
  STL: 'servidor de San Luis',
  SVX: 'servidor de Ekaterimburgo',
  SYD: 'servidor de Sídney',
  SZV: 'servidor de Suzhou',
  TBS: 'servidor de Tiflis',
  TGU: 'servidor de Tegucigalpa',
  TLH: 'servidor de Tallahassee',
  TLL: 'servidor de Tallin',
  TLV: 'servidor de Tel Aviv',
  TNA: 'servidor de Jinan',
  TNR: 'servidor de Antananarivo',
  TPA: 'servidor de Tampa',
  TPE: 'servidor de Taipéi',
  TSN: 'servidor de Tianjin',
  TUN: 'servidor de Túnez',
  TXL: 'servidor de Berlín',
  UIO: 'servidor de Quito',
  ULN: 'servidor de Ulán Bator',
  URT: 'servidor de Surat Thani',
  VCP: 'servidor de Campinas',
  VIE: 'servidor de Viena',
  VNO: 'servidor de Vilna',
  VTE: 'servidor de Vientián',
  WAW: 'servidor de Varsovia',
  WUH: 'servidor de Wuhan',
  WUX: 'servidor de Wuxi',
  XIY: 'servidor de Xi an',
  YUL: 'servidor de Montreal',
  YVR: 'servidor de Vancouver',
  YWG: 'servidor de Winnipeg',
  YXE: 'servidor de Saskatoon',
  YYC: 'servidor de Calgary',
  YYZ: 'servidor de Toronto',
  ZAG: 'servidor de Zagreb',
  ZDM: 'servidor de Ramallah',
  ZRH: 'servidor de Zúrich',
};
